title: "Saheli Datta"
author: "Saheli Datta"
description: "Indian Statistical Institute"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false             # use a dark header
show_social: true          # title description and social media in footer

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "About Me"}
  - {file: "nonparametric.Rmd", title: "Resume"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:sahelidatta320@gmail.com.com"}
  - {title: Github, icon: github, url: "https://github.com/Saheli2001"}
  

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
